/* tslint:disable */
/* eslint-disable */
/**
 * News Hook API
 * API for monitoring and alerting on news and content updates
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgentControllerResponse
 */
export interface AgentControllerResponse {
    /**
     * 
     * @type {string}
     * @memberof AgentControllerResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AgentControllerResponse
     */
    name?: string | null;
    /**
     * Google's unique user ID
     * @type {string}
     * @memberof AgentControllerResponse
     */
    googleId: string;
    /**
     * 
     * @type {string}
     * @memberof AgentControllerResponse
     */
    id: string;
    /**
     * API key for authentication
     * @type {string}
     * @memberof AgentControllerResponse
     */
    apiKey: string;
    /**
     * Credits. In cents of USD
     * @type {number}
     * @memberof AgentControllerResponse
     */
    creditBalance?: number;
    /**
     * 
     * @type {Date}
     * @memberof AgentControllerResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof AgentControllerResponse
     */
    lastLogin?: Date | null;
}

/**
 * Check if a given object implements the AgentControllerResponse interface.
 */
export function instanceOfAgentControllerResponse(value: object): value is AgentControllerResponse {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('googleId' in value) || value['googleId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('apiKey' in value) || value['apiKey'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function AgentControllerResponseFromJSON(json: any): AgentControllerResponse {
    return AgentControllerResponseFromJSONTyped(json, false);
}

export function AgentControllerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentControllerResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'googleId': json['google_id'],
        'id': json['id'],
        'apiKey': json['api_key'],
        'creditBalance': json['credit_balance'] == null ? undefined : json['credit_balance'],
        'createdAt': (new Date(json['created_at'])),
        'lastLogin': json['last_login'] == null ? undefined : (new Date(json['last_login'])),
    };
}

export function AgentControllerResponseToJSON(json: any): AgentControllerResponse {
    return AgentControllerResponseToJSONTyped(json, false);
}

export function AgentControllerResponseToJSONTyped(value?: AgentControllerResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'name': value['name'],
        'google_id': value['googleId'],
        'id': value['id'],
        'api_key': value['apiKey'],
        'credit_balance': value['creditBalance'],
        'created_at': ((value['createdAt']).toISOString()),
        'last_login': value['lastLogin'] == null ? undefined : ((value['lastLogin'] as any).toISOString()),
    };
}

