/* tslint:disable */
/* eslint-disable */
/**
 * News Hook API
 * API for monitoring and alerting on news and content updates
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AlertStatus = {
    Active: 'ACTIVE',
    Triggered: 'TRIGGERED',
    Cancelled: 'CANCELLED',
    Warned: 'WARNED',
    Expired: 'EXPIRED'
} as const;
export type AlertStatus = typeof AlertStatus[keyof typeof AlertStatus];


export function instanceOfAlertStatus(value: any): boolean {
    for (const key in AlertStatus) {
        if (Object.prototype.hasOwnProperty.call(AlertStatus, key)) {
            if (AlertStatus[key as keyof typeof AlertStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AlertStatusFromJSON(json: any): AlertStatus {
    return AlertStatusFromJSONTyped(json, false);
}

export function AlertStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertStatus {
    return json as AlertStatus;
}

export function AlertStatusToJSON(value?: AlertStatus | null): any {
    return value as any;
}

export function AlertStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): AlertStatus {
    return value as AlertStatus;
}

