/* tslint:disable */
/* eslint-disable */
/**
 * News Hook API
 * API for monitoring and alerting on news and content updates
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AlertPromptItem } from './AlertPromptItem';
import {
    AlertPromptItemFromJSON,
    AlertPromptItemFromJSONTyped,
    AlertPromptItemToJSON,
    AlertPromptItemToJSONTyped,
} from './AlertPromptItem';

/**
 * 
 * @export
 * @interface AlertPromptListResponse
 */
export interface AlertPromptListResponse {
    /**
     * 
     * @type {Array<AlertPromptItem>}
     * @memberof AlertPromptListResponse
     */
    alerts: Array<AlertPromptItem>;
    /**
     * 
     * @type {number}
     * @memberof AlertPromptListResponse
     */
    totalCount: number;
}

/**
 * Check if a given object implements the AlertPromptListResponse interface.
 */
export function instanceOfAlertPromptListResponse(value: object): value is AlertPromptListResponse {
    if (!('alerts' in value) || value['alerts'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    return true;
}

export function AlertPromptListResponseFromJSON(json: any): AlertPromptListResponse {
    return AlertPromptListResponseFromJSONTyped(json, false);
}

export function AlertPromptListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertPromptListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'alerts': ((json['alerts'] as Array<any>).map(AlertPromptItemFromJSON)),
        'totalCount': json['total_count'],
    };
}

export function AlertPromptListResponseToJSON(json: any): AlertPromptListResponse {
    return AlertPromptListResponseToJSONTyped(json, false);
}

export function AlertPromptListResponseToJSONTyped(value?: AlertPromptListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alerts': ((value['alerts'] as Array<any>).map(AlertPromptItemToJSON)),
        'total_count': value['totalCount'],
    };
}

