/* tslint:disable */
/* eslint-disable */
/**
 * News Hook API
 * API for monitoring and alerting on news and content updates
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlertPromptCreateSuccessResponse
 */
export interface AlertPromptCreateSuccessResponse {
    /**
     * The ID of the alert
     * @type {string}
     * @memberof AlertPromptCreateSuccessResponse
     */
    id: string;
    /**
     * The natural language prompt describing what to monitor
     * @type {string}
     * @memberof AlertPromptCreateSuccessResponse
     */
    prompt: string;
    /**
     * Reason for the approval or denial
     * @type {string}
     * @memberof AlertPromptCreateSuccessResponse
     */
    reason: string;
    /**
     * 
     * @type {Date}
     * @memberof AlertPromptCreateSuccessResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof AlertPromptCreateSuccessResponse
     */
    keywords?: Array<string> | null;
}

/**
 * Check if a given object implements the AlertPromptCreateSuccessResponse interface.
 */
export function instanceOfAlertPromptCreateSuccessResponse(value: object): value is AlertPromptCreateSuccessResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function AlertPromptCreateSuccessResponseFromJSON(json: any): AlertPromptCreateSuccessResponse {
    return AlertPromptCreateSuccessResponseFromJSONTyped(json, false);
}

export function AlertPromptCreateSuccessResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertPromptCreateSuccessResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'prompt': json['prompt'],
        'reason': json['reason'],
        'createdAt': (new Date(json['created_at'])),
        'keywords': json['keywords'] == null ? undefined : json['keywords'],
    };
}

export function AlertPromptCreateSuccessResponseToJSON(json: any): AlertPromptCreateSuccessResponse {
    return AlertPromptCreateSuccessResponseToJSONTyped(json, false);
}

export function AlertPromptCreateSuccessResponseToJSONTyped(value?: AlertPromptCreateSuccessResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'prompt': value['prompt'],
        'reason': value['reason'],
        'created_at': ((value['createdAt']).toISOString()),
        'keywords': value['keywords'],
    };
}

