/* tslint:disable */
/* eslint-disable */
/**
 * News Hook API
 * API for monitoring and alerting on news and content updates
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LLMModelItem
 */
export interface LLMModelItem {
    /**
     * 
     * @type {string}
     * @memberof LLMModelItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof LLMModelItem
     */
    modelName: string;
    /**
     * 
     * @type {number}
     * @memberof LLMModelItem
     */
    inputTokenPrice: number;
    /**
     * 
     * @type {number}
     * @memberof LLMModelItem
     */
    outputTokenPrice: number;
    /**
     * Whether the model is currently active and can be used
     * @type {boolean}
     * @memberof LLMModelItem
     */
    isActive: boolean;
}

/**
 * Check if a given object implements the LLMModelItem interface.
 */
export function instanceOfLLMModelItem(value: object): value is LLMModelItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('modelName' in value) || value['modelName'] === undefined) return false;
    if (!('inputTokenPrice' in value) || value['inputTokenPrice'] === undefined) return false;
    if (!('outputTokenPrice' in value) || value['outputTokenPrice'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    return true;
}

export function LLMModelItemFromJSON(json: any): LLMModelItem {
    return LLMModelItemFromJSONTyped(json, false);
}

export function LLMModelItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): LLMModelItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'modelName': json['model_name'],
        'inputTokenPrice': json['input_token_price'],
        'outputTokenPrice': json['output_token_price'],
        'isActive': json['is_active'],
    };
}

export function LLMModelItemToJSON(json: any): LLMModelItem {
    return LLMModelItemToJSONTyped(json, false);
}

export function LLMModelItemToJSONTyped(value?: LLMModelItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'model_name': value['modelName'],
        'input_token_price': value['inputTokenPrice'],
        'output_token_price': value['outputTokenPrice'],
        'is_active': value['isActive'],
    };
}

