/* tslint:disable */
/* eslint-disable */
/**
 * News Hook API
 * API for monitoring and alerting on news and content updates
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LLMModelItem } from './LLMModelItem';
import {
    LLMModelItemFromJSON,
    LLMModelItemFromJSONTyped,
    LLMModelItemToJSON,
    LLMModelItemToJSONTyped,
} from './LLMModelItem';

/**
 * 
 * @export
 * @interface LLMModelListResponse
 */
export interface LLMModelListResponse {
    /**
     * 
     * @type {Array<LLMModelItem>}
     * @memberof LLMModelListResponse
     */
    items: Array<LLMModelItem>;
}

/**
 * Check if a given object implements the LLMModelListResponse interface.
 */
export function instanceOfLLMModelListResponse(value: object): value is LLMModelListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function LLMModelListResponseFromJSON(json: any): LLMModelListResponse {
    return LLMModelListResponseFromJSONTyped(json, false);
}

export function LLMModelListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LLMModelListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(LLMModelItemFromJSON)),
    };
}

export function LLMModelListResponseToJSON(json: any): LLMModelListResponse {
    return LLMModelListResponseToJSONTyped(json, false);
}

export function LLMModelListResponseToJSONTyped(value?: LLMModelListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(LLMModelItemToJSON)),
    };
}

