/* tslint:disable */
/* eslint-disable */
/**
 * News Hook API
 * API for monitoring and alerting on news and content updates
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OAuth2Request
 */
export interface OAuth2Request {
    /**
     * Google OAuth2 access token
     * @type {string}
     * @memberof OAuth2Request
     */
    accessToken: string;
}

/**
 * Check if a given object implements the OAuth2Request interface.
 */
export function instanceOfOAuth2Request(value: object): value is OAuth2Request {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    return true;
}

export function OAuth2RequestFromJSON(json: any): OAuth2Request {
    return OAuth2RequestFromJSONTyped(json, false);
}

export function OAuth2RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuth2Request {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
    };
}

export function OAuth2RequestToJSON(json: any): OAuth2Request {
    return OAuth2RequestToJSONTyped(json, false);
}

export function OAuth2RequestToJSONTyped(value?: OAuth2Request | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
    };
}

