/* tslint:disable */
/* eslint-disable */
/**
 * News Hook API
 * API for monitoring and alerting on news and content updates
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDocumentCreateRequest
 */
export interface UserDocumentCreateRequest {
    /**
     * The name of the document
     * @type {string}
     * @memberof UserDocumentCreateRequest
     */
    name: string;
    /**
     * The actual content of the document
     * @type {string}
     * @memberof UserDocumentCreateRequest
     */
    content: string;
}

/**
 * Check if a given object implements the UserDocumentCreateRequest interface.
 */
export function instanceOfUserDocumentCreateRequest(value: object): value is UserDocumentCreateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function UserDocumentCreateRequestFromJSON(json: any): UserDocumentCreateRequest {
    return UserDocumentCreateRequestFromJSONTyped(json, false);
}

export function UserDocumentCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDocumentCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'content': json['content'],
    };
}

export function UserDocumentCreateRequestToJSON(json: any): UserDocumentCreateRequest {
    return UserDocumentCreateRequestToJSONTyped(json, false);
}

export function UserDocumentCreateRequestToJSONTyped(value?: UserDocumentCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'content': value['content'],
    };
}

