/* tslint:disable */
/* eslint-disable */
/**
 * News Hook API
 * API for monitoring and alerting on news and content updates
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LLMModelListResponse,
} from '../models/index';
import {
    LLMModelListResponseFromJSON,
    LLMModelListResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class LlmModelsApi extends runtime.BaseAPI {

    /**
     * List all active LLM models.
     * List Llm Models
     */
    async listLlmModelsApiV1LlmModelsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LLMModelListResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/llm-models/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LLMModelListResponseFromJSON(jsonValue));
    }

    /**
     * List all active LLM models.
     * List Llm Models
     */
    async listLlmModelsApiV1LlmModelsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LLMModelListResponse> {
        const response = await this.listLlmModelsApiV1LlmModelsGetRaw(initOverrides);
        return await response.value();
    }

}
